# Use Python 3.11.4 as the base image
FROM python:3.11.4-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install system libraries for audio processing
RUN apt-get update && apt-get install -y libasound2
RUN apt-get update && apt-get install -y libasound2-dev
RUN apt-get update && apt-get install -y libasound2-plugins

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Run streamlit when the container launches
CMD ["streamlit", "run", "test.py"]
